version: '3'

services:

  db_postgres:
    container_name: db_postgres_mk
    image: postgis/postgis:15-3.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mikeadd
    networks:
      - mk-network

  pgadmin:
    container_name: pgadmin_mk
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ibarramiguel119@gmail.com
      PGADMIN_DEFAULT_PASSWORD: mkroot
    ports:
      - "5050:80"
    depends_on:
      - db_postgres
    networks:
      - mk-network

  web:
    container_name: web_mk
    build: ./Backend/proyect_web_v1
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - "8000"
    volumes:
      - ./Backend/proyect_web_v1:/app
      - static:/app/static
    depends_on:
      - db_postgres
    environment:
      GDAL_LIBRARY_PATH: /usr/lib/libgdal.so
      DJANGO_SECRET_KEY: django-inseguro
      DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1
    networks:
      - mk-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_mk
    networks:
      - mk-network
    # NO expone puertos
    # Solo genera el build para nginx

  nginx:
    image: nginx:1.25
    container_name: proyect_v1-nginx-1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/build:/usr/share/nginx/html:ro
      - ./config/nginx/conf.d:/etc/nginx/conf.d:ro
      - static:/app/static
    depends_on:
      - web
    networks:
      - mk-network

volumes:
  postgres_data:
  static:

networks:
  mk-network:
    driver: bridge
