server {
    listen 80;
    server_name localhost;
    client_max_body_size 100M;

    # Redirigir la raíz a la aplicación React (frontend)
    location / {
        proxy_pass http://frontend_mk:3000;  
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # Redirigir a Django para las solicitudes API o cualquier ruta bajo "/api/"
    location /api/ {
        proxy_pass http://web_mk:8000;  # Contenedor Django en el puerto 8000
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # Archivos estáticos de React (que estarán en la carpeta build después de 'npm run build')
    location /static/ {
        alias /usr/share/nginx/html/static/;  # Ruta donde Nginx servirá los archivos estáticos generados por React
        expires 30d;
        add_header Cache-Control public;
    }

    # Archivos de medios de Django (si los tienes)
    location /media/ {
        alias /app/media/;  # Ajusta esta ruta si los archivos media están en una ubicación diferente
    }

    # WebSockets (si los utilizas en Django)
    location /ws/ {
        proxy_pass http://web_mk:8000;  # Contenedor Django
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
